language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install . --quiet
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib --quiet --use-mirrors; fi"
  - pip install tox simplejson Flask-SQLAlchemy Flask-MongoEngine Flask-Peewee bcrypt --quiet

services:
  - mongodb

script: tox

branches:
  only:
    - develop
