language: python

python:
  - 2.5
  - 2.6
  - 2.7

install: 
  - pip install Flask Flask-Login Flask-Principal Flask-WTF Flask-Mail passlib nose Flask-SQLAlchemy Flask-MongoEngine pybcrypt --use-mirrors
  - pip install . --use-mirrors

script: nosetests